export const copy = {
  tabs: {
    pagos: 'Pagos',
    bdv: 'BDV',
    ajustes: 'Ajustes',
  },
  pagos: {
    title: 'Pagos',
    subtitle: 'PagomóvilBDV → factura',
    loading: 'Cargando registros…',
    emptyTitle: 'Esperando PagomóvilBDV',
    emptyDescription: 'Los pagos BDV aparecerán aquí al recibir una notificación.',
    manualRegister: 'Registro manual',
    sessionExpired: 'Sesión expirada — inicia sesión de nuevo en Ajustes.',
    connectPrompt: 'Conecta kd-gym en Ajustes para sincronizar facturas.',
    pendingSync: (count: number) =>
      `${count} pago(s) pendiente(s) de sincronizar con kd-gym.`,
    goToSettings: 'Ir a Ajustes',
  },
  ajustes: {
    title: 'Ajustes',
    subtitle: 'Privacidad, sincronización y almacenamiento',
    connectionTitle: 'Conexión kd-gym',
    appearanceTitle: 'Apariencia',
    storageTitle: 'Almacenamiento',
    diagnosticsTitle: 'Diagnóstico',
    themeDark: 'Oscuro',
    themeLight: 'Claro',
    themeSystem: 'Sistema',
    retention: 'Retención',
    rawPayload: 'Guardar payload crudo (depuración)',
    notificationAccess: 'Acceso a notificaciones',
    enabled: 'Activo',
    disabled: 'Inactivo',
    clearHistoryTitle: '¿Borrar todo el historial?',
    clearHistoryBody: 'Esta acción no se puede deshacer.',
    clearCacheTitle: '¿Limpiar caché local?',
    clearCacheBody: 'No borra registros en kd-gym.',
    cancel: 'Cancelar',
    clear: 'Borrar',
    login: 'Iniciar sesión',
    loggingIn: 'Conectando…',
    logout: 'Cerrar sesión',
    testConnection: 'Probar conexión',
    testing: 'Probando…',
    syncPayments: 'Sincronizar pagos',
    retryFailed: 'Reintentar fallidos',
    clearLocalCache: 'Limpiar caché local',
    rescanBdv: 'Re-escanear notificaciones BDV',
    openNotificationSettings: 'Abrir ajustes de notificaciones',
    syncFromShade: 'Sincronizar desde barra de notificaciones',
    applyRetention: 'Aplicar retención ahora',
    clearAllHistory: 'Borrar todo el historial',
    batterySettings: 'Optimización de batería',
    runSetup: 'Repetir configuración',
  },
  onboarding: {
    welcomeTitle: 'KD-Gym Pagos',
    welcomeSubtitle: 'Captura alertas BDV y sincroniza pagos con kd-gym.',
    welcomeHeroTitle: 'Solo Banco de Venezuela',
    welcomeHeroBody:
      'Activa el acceso a notificaciones en Android y registra PagomóvilBDV automáticamente.',
    getStarted: 'Comenzar',
    step: (current: number, total: number) => `Paso ${current} de ${total}`,
  },
  syncStatus: {
    clientAssigned: 'Cliente asociado',
    paid: 'Pagado',
    invoicePending: 'Factura pendiente',
    pendingSync: 'Pendiente de sync',
    syncFailed: 'Error de sincronización',
    registered: 'Registrado',
    duplicate: 'Duplicado',
    hiddenContent: 'Contenido oculto',
  },
  clients: {
    noResults: 'Sin clientes encontrados',
    noResultsHint: 'Prueba otro nombre o crea un cliente nuevo.',
    searchError: 'No se pudo buscar clientes. Intenta de nuevo.',
    retry: 'Reintentar',
  },
} as const;
