export const copy = {
  tabs: {
    pagos: 'Pagos',
    bdv: 'BDV',
    ajustes: 'Ajustes',
  },
  pagos: {
    title: 'Pagos',
    subtitle: 'PagomóvilBDV → factura',
    loading: 'Cargando registros…',
    emptyTitle: 'Esperando PagomóvilBDV',
    emptyDescription: 'Los pagos BDV aparecerán aquí al recibir una notificación.',
    manualRegister: 'Registro manual',
    sessionExpired: 'Sesión expirada — inicia sesión de nuevo en Ajustes.',
    connectPrompt: 'Conecta kd-gym en Ajustes para sincronizar facturas.',
    pendingSync: (count: number) =>
      `${count} pago(s) pendiente(s) de sincronizar con kd-gym.`,
    goToSettings: 'Ir a Ajustes',
    actions: {
      confirm: {
        completedTitle: 'Pago confirmado',
        completedMessage: (summary: string) =>
          `${summary} — factura marcada como pagada en kd-gym.`,
        completedMessageGeneric: 'La factura fue marcada como pagada en kd-gym.',
        queuedTitle: 'Confirmación guardada',
        queuedMessage: (summary: string) =>
          `${summary} — se aplicará en kd-gym cuando haya conexión.`,
        queuedMessageGeneric:
          'La confirmación se aplicará en kd-gym en cuanto haya conexión.',
        alreadyTitle: 'Ya estaba confirmado',
        alreadyMessage: (summary: string) => `${summary} — este pago ya fue confirmado antes.`,
        alreadyMessageGeneric: 'Este pago ya fue confirmado anteriormente.',
        nextStep: 'Siguiente paso: asocia el cliente de kd-gym a este pago.',
        confirming: 'Confirmando pago…',
      },
      assign: {
        completedTitle: 'Cliente asociado',
        completedMessage: (client: string, summary: string) =>
          summary
            ? `${client} vinculado al pago de ${summary}.`
            : `${client} vinculado correctamente en kd-gym.`,
        queuedTitle: 'Asociación guardada',
        queuedMessage: (client: string, summary: string) =>
          summary
            ? `${client} se vinculará al pago de ${summary} al sincronizar.`
            : `${client} se vinculará en kd-gym al sincronizar el pago.`,
        alreadyTitle: 'Ya tenía cliente',
        alreadyMessage: (client: string, summary: string) =>
          summary
            ? `Este pago de ${summary} ya tenía un cliente asociado.`
            : 'Este pago ya tenía un cliente asociado.',
        clientFallback: 'El cliente',
        assigning: 'Asociando cliente…',
        assignCta: 'Asociar cliente',
      },
    },
  },
  ajustes: {
    title: 'Ajustes',
    subtitle: 'Privacidad, sincronización y almacenamiento',
    connectionTitle: 'Conexión kd-gym',
    appearanceTitle: 'Apariencia',
    storageTitle: 'Almacenamiento',
    diagnosticsTitle: 'Diagnóstico',
    themeDark: 'Oscuro',
    themeLight: 'Claro',
    themeSystem: 'Sistema',
    retention: 'Retención',
    rawPayload: 'Guardar payload crudo (depuración)',
    notificationAccess: 'Acceso a notificaciones',
    enabled: 'Activo',
    disabled: 'Inactivo',
    clearHistoryTitle: '¿Borrar todo el historial?',
    clearHistoryBody: 'Esta acción no se puede deshacer.',
    clearCacheTitle: '¿Limpiar caché local?',
    clearCacheBody: 'No borra registros en kd-gym.',
    cancel: 'Cancelar',
    clear: 'Borrar',
    login: 'Iniciar sesión',
    loggingIn: 'Conectando…',
    logout: 'Cerrar sesión',
    testConnection: 'Probar conexión',
    testing: 'Probando…',
    syncPayments: 'Sincronizar pagos',
    retryFailed: 'Reintentar fallidos',
    clearLocalCache: 'Limpiar caché local',
    rescanBdv: 'Re-escanear notificaciones BDV',
    openNotificationSettings: 'Abrir ajustes de notificaciones',
    syncFromShade: 'Sincronizar desde barra de notificaciones',
    applyRetention: 'Aplicar retención ahora',
    clearAllHistory: 'Borrar todo el historial',
    batterySettings: 'Optimización de batería',
    runSetup: 'Repetir configuración',
  },
  onboarding: {
    welcomeTitle: 'KD-Gym Pagos',
    welcomeSubtitle: 'Captura alertas BDV y sincroniza pagos con kd-gym.',
    welcomeHeroTitle: 'Solo Banco de Venezuela',
    welcomeHeroBody:
      'Activa el acceso a notificaciones en Android y registra PagomóvilBDV automáticamente.',
    getStarted: 'Comenzar',
    step: (current: number, total: number) => `Paso ${current} de ${total}`,
  },
  syncStatus: {
    clientAssigned: 'Cliente asociado',
    paid: 'Pagado',
    invoicePending: 'Factura pendiente',
    pendingSync: 'Pendiente de sync',
    syncFailed: 'Error de sincronización',
    registered: 'Registrado',
    duplicate: 'Duplicado',
    hiddenContent: 'Contenido oculto',
  },
  clients: {
    noResults: 'Sin clientes encontrados',
    noResultsHint: 'Prueba otro nombre o crea un cliente nuevo.',
    searchError: 'No se pudo buscar clientes. Intenta de nuevo.',
    retry: 'Reintentar',
  },
  feedback: {
    confirmQueued: 'El pago se confirmará cuando haya conexión con kd-gym.',
    confirmCompleted: 'Factura actualizada en kd-gym.',
    assignQueued: 'El cliente se asociará cuando el pago esté sincronizado con kd-gym.',
    assignCompleted: 'Cliente vinculado en kd-gym.',
    syncComplete: 'Sincronización completa',
    syncFailed: 'No se pudo sincronizar',
    syncInFlight: 'Sincronización en curso',
    captureDetected: 'Nuevo pago detectado',
    captureDuplicate: 'Pago ya registrado',
    queueRetryDone: 'Reintento completado',
    sessionClosed: 'Sesión cerrada',
    connected: 'Conectado',
    skipConnect: 'Podrás conectar kd-gym después en Ajustes.',
    noActivity: 'Sin actividad reciente',
    clearActivity: 'Limpiar actividad',
  },
} as const;
